// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modbot.Cloud.Engine;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modbot.Cloud.Engine.Migrations
{
    [DbContext(typeof(EngineContext))]
    [Migration("20260915080209_CreateEngine")]
    partial class CreateEngine
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modbot.Cloud.Engine.EventHourTotal", b =>
                {
                    b.Property<string>("Type")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("Hour")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hour");

                    b.Property<long>("Events")
                        .HasColumnType("bigint")
                        .HasColumnName("events");

                    b.HasKey("Type", "Hour")
                        .HasName("pk_event_hour_total");

                    b.ToTable("event_hour_total", (string)null);
                });

            modelBuilder.Entity("Modbot.Cloud.Engine.InstallClock", b =>
                {
                    b.Property<Guid>("InstallId")
                        .HasColumnType("uuid")
                        .HasColumnName("install_id");

                    b.Property<long>("AppliedOffsetMs")
                        .HasColumnType("bigint")
                        .HasColumnName("applied_offset_ms");

                    b.Property<long>("Batches")
                        .HasColumnType("bigint")
                        .HasColumnName("batches");

                    b.Property<bool>("Disagrees")
                        .HasColumnType("boolean")
                        .HasColumnName("disagrees");

                    b.Property<long>("ObservedOffsetMs")
                        .HasColumnType("bigint")
                        .HasColumnName("observed_offset_ms");

                    b.Property<string>("ReportedConfidence")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("reported_confidence");

                    b.Property<long>("ReportedOffsetMs")
                        .HasColumnType("bigint")
                        .HasColumnName("reported_offset_ms");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("InstallId")
                        .HasName("pk_install_clock");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_install_clock_updated_at");

                    b.ToTable("install_clock", (string)null);
                });

            modelBuilder.Entity("Modbot.Cloud.Engine.LineDayTotal", b =>
                {
                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<Guid>("InstallId")
                        .HasColumnType("uuid")
                        .HasColumnName("install_id");

                    b.Property<long>("Lines")
                        .HasColumnType("bigint")
                        .HasColumnName("lines");

                    b.HasKey("Day", "InstallId")
                        .HasName("pk_line_day_total");

                    b.HasIndex("InstallId", "Day")
                        .HasDatabaseName("ix_line_day_total_install_id_day");

                    b.ToTable("line_day_total", (string)null);
                });

            modelBuilder.Entity("Modbot.Cloud.Engine.LogEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<Guid>("InstallId")
                        .HasColumnType("uuid")
                        .HasColumnName("install_id");

                    b.Property<long>("LineOffset")
                        .HasColumnType("bigint")
                        .HasColumnName("line_offset");

                    b.Property<long>("LogFileId")
                        .HasColumnType("bigint")
                        .HasColumnName("log_file_id");

                    b.Property<DateTimeOffset?>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("ParsedBy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("parsed_by");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("type");

                    b.Property<string>("TypeRaw")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("type_raw");

                    b.HasKey("Id", "ReceivedAt")
                        .HasName("pk_log_event");

                    b.HasIndex("Type", "OccurredAt")
                        .HasDatabaseName("ix_log_event_type_occurred_at");

                    b.ToTable("log_event", (string)null);
                });

            modelBuilder.Entity("Modbot.Cloud.Engine.LogFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("FirstReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_received_at");

                    b.Property<Guid>("InstallId")
                        .HasColumnType("uuid")
                        .HasColumnName("install_id");

                    b.Property<DateTimeOffset>("LastReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_received_at");

                    b.Property<long>("LinesStored")
                        .HasColumnType("bigint")
                        .HasColumnName("lines_stored");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<long>("StoredThrough")
                        .HasColumnType("bigint")
                        .HasColumnName("stored_through");

                    b.HasKey("Id")
                        .HasName("pk_log_file");

                    b.HasIndex("LastReceivedAt")
                        .HasDatabaseName("ix_log_file_last_received_at");

                    b.HasIndex("InstallId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_log_file_install_id_name");

                    b.ToTable("log_file", (string)null);
                });

            modelBuilder.Entity("Modbot.Cloud.Engine.LogLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<Guid>("InstallId")
                        .HasColumnType("uuid")
                        .HasColumnName("install_id");

                    b.Property<long>("LineOffset")
                        .HasColumnType("bigint")
                        .HasColumnName("line_offset");

                    b.Property<long>("LogFileId")
                        .HasColumnType("bigint")
                        .HasColumnName("log_file_id");

                    b.Property<DateTime?>("LoggedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("logged_at");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<short?>("UtcOffsetMinutes")
                        .HasColumnType("smallint")
                        .HasColumnName("utc_offset_minutes");

                    b.HasKey("Id", "ReceivedAt")
                        .HasName("pk_log_line");

                    b.HasIndex("InstallId", "ReceivedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_log_line_install_id_received_at");

                    b.ToTable("log_line", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
