// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modbot.Cloud.Engine;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modbot.Cloud.Engine.Migrations
{
    [DbContext(typeof(EngineContext))]
    [Migration("20260916143902_AddInstanceLogs")]
    partial class AddInstanceLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modbot.Cloud.Engine.EventDayTotal", b =>
                {
                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<Guid>("InstallId")
                        .HasColumnType("uuid")
                        .HasColumnName("install_id");

                    b.Property<long>("Events")
                        .HasColumnType("bigint")
                        .HasColumnName("events");

                    b.HasKey("Day", "InstallId")
                        .HasName("pk_event_day_total");

                    b.HasIndex("InstallId", "Day")
                        .HasDatabaseName("ix_event_day_total_install_id_day");

                    b.ToTable("event_day_total", (string)null);
                });

            modelBuilder.Entity("Modbot.Cloud.Engine.EventHourTotal", b =>
                {
                    b.Property<string>("Type")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("Hour")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hour");

                    b.Property<long>("Events")
                        .HasColumnType("bigint")
                        .HasColumnName("events");

                    b.HasKey("Type", "Hour")
                        .HasName("pk_event_hour_total");

                    b.ToTable("event_hour_total", (string)null);
                });

            modelBuilder.Entity("Modbot.Cloud.Engine.InstallClock", b =>
                {
                    b.Property<Guid>("InstallId")
                        .HasColumnType("uuid")
                        .HasColumnName("install_id");

                    b.Property<long>("AppliedOffsetMs")
                        .HasColumnType("bigint")
                        .HasColumnName("applied_offset_ms");

                    b.Property<long>("Batches")
                        .HasColumnType("bigint")
                        .HasColumnName("batches");

                    b.Property<bool>("Disagrees")
                        .HasColumnType("boolean")
                        .HasColumnName("disagrees");

                    b.Property<long>("ObservedOffsetMs")
                        .HasColumnType("bigint")
                        .HasColumnName("observed_offset_ms");

                    b.Property<string>("ReportedConfidence")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("reported_confidence");

                    b.Property<long>("ReportedOffsetMs")
                        .HasColumnType("bigint")
                        .HasColumnName("reported_offset_ms");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("InstallId")
                        .HasName("pk_install_clock");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_install_clock_updated_at");

                    b.ToTable("install_clock", (string)null);
                });

            modelBuilder.Entity("Modbot.Cloud.Engine.InstanceLogLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("Area")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("area");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("Exception")
                        .HasColumnType("text")
                        .HasColumnName("exception");

                    b.Property<Guid>("InstallId")
                        .HasColumnType("uuid")
                        .HasColumnName("install_id");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Properties")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("properties");

                    b.Property<string>("Service")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("service");

                    b.Property<string>("Source")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source");

                    b.Property<string>("Template")
                        .HasColumnType("text")
                        .HasColumnName("template");

                    b.Property<string>("Version")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("version");

                    b.HasKey("Id", "ReceivedAt")
                        .HasName("pk_instance_log");

                    b.HasIndex("InstallId", "ReceivedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_instance_log_install_received_at");

                    b.HasIndex("Level", "ReceivedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_instance_log_level_received_at");

                    b.ToTable("instance_log", (string)null);
                });

            modelBuilder.Entity("Modbot.Cloud.Engine.StoredEvent", b =>
                {
                    b.Property<Guid>("InstallId")
                        .HasColumnType("uuid")
                        .HasColumnName("install_id");

                    b.Property<string>("ClientEventId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("client_event_id");

                    b.Property<string>("ClientVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("client_version");

                    b.Property<int>("ClockAdjustmentMs")
                        .HasColumnType("integer")
                        .HasColumnName("clock_adjustment_ms");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<string>("GroupId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("group_id");

                    b.Property<string>("InstanceId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("instance_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<DateTimeOffset?>("OccurredBefore")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_before");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("subject_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("type");

                    b.Property<string>("TypeRaw")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("type_raw");

                    b.Property<string>("WorldId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("world_id");

                    b.HasKey("InstallId", "ClientEventId")
                        .HasName("pk_client_event");

                    b.HasIndex("ReceivedAt")
                        .HasDatabaseName("ix_client_event_received_at");

                    b.HasIndex("InstallId", "ReceivedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_client_event_install_id_received_at");

                    b.HasIndex("Type", "OccurredAt")
                        .HasDatabaseName("ix_client_event_type_occurred_at");

                    b.ToTable("client_event", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
