<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Modbot.Core\Modbot.Core.csproj" />
    <ProjectReference Include="..\Modbot.VRChat\Modbot.VRChat.csproj" />
    <ProjectReference Include="..\Modbot.Analytics\Modbot.Analytics.csproj" />
    <ProjectReference Include="..\Modbot.Evidence\Modbot.Evidence.csproj" />
    <ProjectReference Include="..\Modbot.AI\Modbot.AI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="ModelContextProtocol.AspNetCore" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
