<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Modbot.Core\Modbot.Core.csproj" />
    <ProjectReference Include="..\Modbot.Analytics\Modbot.Analytics.csproj" />
    <ProjectReference Include="..\Modbot.Moderation\Modbot.Moderation.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenAI" />
    <PackageReference Include="NodaTime" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
