// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modbot.Cloud.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modbot.Cloud.Data.Migrations
{
    [DbContext(typeof(CloudContext))]
    [Migration("20260916153100_LogsBelongToTheRegisteredServer")]
    partial class LogsBelongToTheRegisteredServer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modbot.Cloud.Features.Accounts.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<DateTimeOffset?>("LastSignedInAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_signed_in_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PendingEmail")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("pending_email");

                    b.HasKey("Id")
                        .HasName("pk_account");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_account_created_at");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_account_email");

                    b.ToTable("account", (string)null);
                });

            modelBuilder.Entity("Modbot.Cloud.Features.Accounts.AccountSession", b =>
                {
                    b.Property<string>("TokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.HasKey("TokenHash")
                        .HasName("pk_account_session");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_account_session_account_id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_account_session_expires_at");

                    b.ToTable("account_session", (string)null);
                });

            modelBuilder.Entity("Modbot.Cloud.Features.Accounts.AccountToken", b =>
                {
                    b.Property<string>("TokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("purpose");

                    b.HasKey("TokenHash")
                        .HasName("pk_account_token");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_account_token_expires_at");

                    b.HasIndex("AccountId", "Purpose")
                        .HasDatabaseName("ix_account_token_account_id_purpose");

                    b.ToTable("account_token", (string)null);
                });

            modelBuilder.Entity("Modbot.Cloud.Features.Admin.AdminSession", b =>
                {
                    b.Property<string>("TokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.HasKey("TokenHash")
                        .HasName("pk_admin_session");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_admin_session_expires_at");

                    b.ToTable("admin_session", (string)null);
                });

            modelBuilder.Entity("Modbot.Cloud.Features.Installs.Install", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClientVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("client_version");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("ModbotServerId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("modbot_server_id");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("platform");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("secret_hash");

                    b.HasKey("Id")
                        .HasName("pk_install");

                    b.HasIndex("LastSeenAt")
                        .HasDatabaseName("ix_install_last_seen_at");

                    b.ToTable("install", (string)null);
                });

            modelBuilder.Entity("Modbot.Cloud.Features.InstanceAlerts.InstanceAlert", b =>
                {
                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid")
                        .HasColumnName("server_id");

                    b.Property<string>("Detail")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("detail");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<int>("ErrorsAnHour")
                        .HasColumnType("integer")
                        .HasColumnName("errors_an_hour");

                    b.Property<string>("LastError")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LastSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sent_at");

                    b.Property<bool>("On")
                        .HasColumnType("boolean")
                        .HasColumnName("watched");

                    b.Property<bool>("Problem")
                        .HasColumnType("boolean")
                        .HasColumnName("problem");

                    b.Property<int>("QuietHours")
                        .HasColumnType("integer")
                        .HasColumnName("quiet_hours");

                    b.Property<int>("SilentAfterMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("silent_after_minutes");

                    b.Property<DateTimeOffset?>("Since")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("since");

                    b.HasKey("ServerId")
                        .HasName("pk_instance_alert");

                    b.HasIndex("On")
                        .HasDatabaseName("ix_instance_alert_watched");

                    b.ToTable("instance_alert", (string)null);
                });

            modelBuilder.Entity("Modbot.Cloud.Features.PublicRooms.PublicRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("JoinLink")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("join_link");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("location");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<string>("Region")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("region");

                    b.Property<DateTimeOffset>("ReportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reported_at");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid")
                        .HasColumnName("server_id");

                    b.Property<string>("WorldId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("world_id");

                    b.Property<string>("WorldImageUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("world_image_url");

                    b.Property<string>("WorldName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("world_name");

                    b.HasKey("Id")
                        .HasName("pk_public_room");

                    b.HasIndex("ServerId", "Location")
                        .IsUnique()
                        .HasDatabaseName("ix_public_room_server_id_location");

                    b.ToTable("public_room", (string)null);
                });

            modelBuilder.Entity("Modbot.Cloud.Features.PublicRooms.RoomsServer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("FirstReportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_reported_at");

                    b.Property<string>("GroupBannerUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("group_banner_url");

                    b.Property<string>("GroupIconUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("group_icon_url");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("group_id");

                    b.Property<string>("GroupName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("group_name");

                    b.Property<DateTimeOffset>("LastReportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_reported_at");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("secret_hash");

                    b.HasKey("Id")
                        .HasName("pk_rooms_server");

                    b.HasIndex("GroupId")
                        .IsUnique()
                        .HasDatabaseName("ix_rooms_server_group_id");

                    b.HasIndex("LastReportedAt")
                        .HasDatabaseName("ix_rooms_server_last_reported_at");

                    b.ToTable("rooms_server", (string)null);
                });

            modelBuilder.Entity("Modbot.Cloud.Features.Registry.RegisteredServer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<bool?>("AiModerationEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("ai_moderation_enabled");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at");

                    b.Property<bool?>("DiscordConnected")
                        .HasColumnType("boolean")
                        .HasColumnName("discord_connected");

                    b.Property<string>("GroupBannerUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("group_banner_url");

                    b.Property<string>("GroupDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("group_description");

                    b.Property<string>("GroupIconUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("group_icon_url");

                    b.Property<string>("GroupId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("group_id");

                    b.Property<string>("GroupName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("group_name");

                    b.Property<string>("HostPlatform")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("host_platform");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset?>("LastReportAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_report_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<DateTimeOffset?>("LinkCodeExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("link_code_expires_at");

                    b.Property<string>("LinkCodeHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("link_code_hash");

                    b.Property<string>("PublicAddress")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("public_address");

                    b.Property<int?>("RateLimitColdStops")
                        .HasColumnType("integer")
                        .HasColumnName("rate_limit_cold_stops");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("secret_hash");

                    b.PrimitiveCollection<List<string>>("TermListsImported")
                        .HasColumnType("text[]")
                        .HasColumnName("term_lists_imported");

                    b.Property<string>("Version")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("version");

                    b.Property<int?>("WafBlocks")
                        .HasColumnType("integer")
                        .HasColumnName("waf_blocks");

                    b.HasKey("Id")
                        .HasName("pk_registered_server");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_registered_server_account_id");

                    b.HasIndex("LastSeenAt")
                        .HasDatabaseName("ix_registered_server_last_seen_at");

                    b.HasIndex("LinkCodeHash")
                        .IsUnique()
                        .HasDatabaseName("ix_registered_server_link_code_hash");

                    b.HasIndex("PublicAddress")
                        .HasDatabaseName("ix_registered_server_public_address");

                    b.ToTable("registered_server", (string)null);
                });

            modelBuilder.Entity("Modbot.Cloud.Features.Registry.ServerReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool?>("AiModerationEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("ai_moderation_enabled");

                    b.Property<bool?>("DiscordConnected")
                        .HasColumnType("boolean")
                        .HasColumnName("discord_connected");

                    b.Property<string>("GroupId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("group_id");

                    b.Property<string>("GroupName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("group_name");

                    b.Property<string>("HostPlatform")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("host_platform");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("PublicAddress")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("public_address");

                    b.Property<int?>("RateLimitColdStops")
                        .HasColumnType("integer")
                        .HasColumnName("rate_limit_cold_stops");

                    b.Property<DateTimeOffset>("ReportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reported_at");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid")
                        .HasColumnName("server_id");

                    b.PrimitiveCollection<List<string>>("TermListsImported")
                        .HasColumnType("text[]")
                        .HasColumnName("term_lists_imported");

                    b.Property<string>("Version")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("version");

                    b.Property<int?>("WafBlocks")
                        .HasColumnType("integer")
                        .HasColumnName("waf_blocks");

                    b.HasKey("Id")
                        .HasName("pk_server_report");

                    b.HasIndex("ServerId", "ReportedAt")
                        .HasDatabaseName("ix_server_report_server_id_reported_at");

                    b.ToTable("server_report", (string)null);
                });

            modelBuilder.Entity("Modbot.Cloud.Features.Retention.CloudSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("EventKeepDays")
                        .HasColumnType("integer")
                        .HasColumnName("event_keep_days");

                    b.Property<int>("LogKeepDays")
                        .HasColumnType("integer")
                        .HasColumnName("log_keep_days");

                    b.HasKey("Id")
                        .HasName("pk_settings");

                    b.ToTable("settings", null, t =>
                        {
                            t.HasCheckConstraint("ck_settings_single_row", "id = 1");
                        });
                });

            modelBuilder.Entity("Modbot.Cloud.Features.Showcase.ShowcaseEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<string>("GroupBannerUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("group_banner_url");

                    b.Property<string>("GroupImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("group_image_url");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("image_url");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("link");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("VRChatGroupId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("vr_chat_group_id");

                    b.HasKey("Id")
                        .HasName("pk_showcase_entry");

                    b.HasIndex("Kind", "SortOrder")
                        .HasDatabaseName("ix_showcase_entry_kind_order");

                    b.ToTable("showcase_entry", (string)null);
                });

            modelBuilder.Entity("Modbot.Cloud.Features.Site.PageInstance", b =>
                {
                    b.Property<string>("InstanceUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("instance_url");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<int>("Visits")
                        .HasColumnType("integer")
                        .HasColumnName("visits");

                    b.HasKey("InstanceUrl")
                        .HasName("pk_page_instance");

                    b.HasIndex("LastSeenAt")
                        .HasDatabaseName("ix_page_instance_last_seen_at");

                    b.ToTable("page_instance", (string)null);
                });

            modelBuilder.Entity("Modbot.Cloud.Features.Site.VisitorInstance", b =>
                {
                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("InstanceUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("instance_url");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<DateTimeOffset>("LastVisitAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_visit_at");

                    b.Property<int>("Visits")
                        .HasColumnType("integer")
                        .HasColumnName("visits");

                    b.HasKey("IpAddress", "InstanceUrl")
                        .HasName("pk_visitor_instance");

                    b.HasIndex("InstanceUrl")
                        .HasDatabaseName("ix_visitor_instance_instance_url");

                    b.ToTable("visitor_instance", (string)null);
                });

            modelBuilder.Entity("Modbot.Cloud.Features.Accounts.AccountSession", b =>
                {
                    b.HasOne("Modbot.Cloud.Features.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_account_session_account_account_id");
                });

            modelBuilder.Entity("Modbot.Cloud.Features.Accounts.AccountToken", b =>
                {
                    b.HasOne("Modbot.Cloud.Features.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_account_token_account_account_id");
                });

            modelBuilder.Entity("Modbot.Cloud.Features.Registry.RegisteredServer", b =>
                {
                    b.HasOne("Modbot.Cloud.Features.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_registered_server_account_account_id");
                });

            modelBuilder.Entity("Modbot.Cloud.Features.Registry.ServerReport", b =>
                {
                    b.HasOne("Modbot.Cloud.Features.Registry.RegisteredServer", null)
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_server_report_registered_server_server_id");
                });
#pragma warning restore 612, 618
        }
    }
}
