// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modbot.Core.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modbot.Core.Data.Migrations
{
    [DbContext(typeof(ModbotContext))]
    [Migration("20260912231219_AddProtectorKey")]
    partial class AddProtectorKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modbot.Core.Data.Entities.ProtectorKey", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<byte[]>("Key")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("key");

                    b.HasKey("Id")
                        .HasName("pk_protector_key");

                    b.ToTable("protector_key", null, t =>
                        {
                            t.HasCheckConstraint("ck_protector_key_singleton", "id = 1");
                        });
                });

            modelBuilder.Entity("Modbot.Core.Data.Entities.Settings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("DedupWindowSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("dedup_window_seconds");

                    b.Property<string>("ManagedGroupId")
                        .HasColumnType("text")
                        .HasColumnName("managed_group_id");

                    b.Property<string>("ManagedGroupName")
                        .HasColumnType("text")
                        .HasColumnName("managed_group_name");

                    b.Property<int>("ModerationFactRetentionDays")
                        .HasColumnType("integer")
                        .HasColumnName("moderation_fact_retention_days");

                    b.Property<bool>("OnboardingComplete")
                        .HasColumnType("boolean")
                        .HasColumnName("onboarding_complete");

                    b.Property<int>("PresenceFactRetentionDays")
                        .HasColumnType("integer")
                        .HasColumnName("presence_fact_retention_days");

                    b.Property<string>("ProxyPasswordEncrypted")
                        .HasColumnType("text")
                        .HasColumnName("proxy_password_encrypted");

                    b.Property<string>("ProxyUrl")
                        .HasColumnType("text")
                        .HasColumnName("proxy_url");

                    b.Property<string>("ProxyUsername")
                        .HasColumnType("text")
                        .HasColumnName("proxy_username");

                    b.Property<bool>("RequireModerationClassification")
                        .HasColumnType("boolean")
                        .HasColumnName("require_moderation_classification");

                    b.Property<string>("VRChatAuthCookieEncrypted")
                        .HasColumnType("text")
                        .HasColumnName("vr_chat_auth_cookie_encrypted");

                    b.Property<string>("VRChatPasswordEncrypted")
                        .HasColumnType("text")
                        .HasColumnName("vr_chat_password_encrypted");

                    b.Property<string>("VRChatTotpSecretEncrypted")
                        .HasColumnType("text")
                        .HasColumnName("vr_chat_totp_secret_encrypted");

                    b.Property<string>("VRChatUsername")
                        .HasColumnType("text")
                        .HasColumnName("vr_chat_username");

                    b.HasKey("Id")
                        .HasName("pk_settings");

                    b.ToTable("settings", null, t =>
                        {
                            t.HasCheckConstraint("ck_settings_singleton", "id = 1");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
