// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modbot.Core.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modbot.Core.Data.Migrations
{
    [DbContext(typeof(ModbotContext))]
    [Migration("20260913201606_AddVRChatUsers")]
    partial class AddVRChatUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .HasColumnType("text")
                        .HasColumnName("xml");

                    b.HasKey("Id")
                        .HasName("pk_data_protection_keys");

                    b.ToTable("data_protection_keys", (string)null);
                });

            modelBuilder.Entity("Modbot.Core.Data.Entities.ClientDeviceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClientVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("client_version");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("device_name");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<Guid>("IssuedToUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("issued_to_user_id");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("platform");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_client_device");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_client_device_token_hash");

                    b.ToTable("client_device", (string)null);
                });

            modelBuilder.Entity("Modbot.Core.Data.Entities.ClientPairingCodeRecord", b =>
                {
                    b.Property<string>("CodeHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<Guid>("IssuedToUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("issued_to_user_id");

                    b.Property<DateTimeOffset?>("RedeemedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("redeemed_at");

                    b.HasKey("CodeHash")
                        .HasName("pk_client_pairing_code");

                    b.ToTable("client_pairing_code", (string)null);
                });

            modelBuilder.Entity("Modbot.Core.Data.Entities.DailyTotal", b =>
                {
                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<string>("Metric")
                        .HasColumnType("text")
                        .HasColumnName("metric");

                    b.Property<string>("Dimension")
                        .HasColumnType("text")
                        .HasColumnName("dimension");

                    b.Property<short>("Origin")
                        .HasColumnType("smallint")
                        .HasColumnName("origin");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric")
                        .HasColumnName("value");

                    b.HasKey("Day", "Metric", "Dimension")
                        .HasName("pk_modbot_daily_total");

                    b.HasIndex("Metric", "Day")
                        .HasDatabaseName("ix_modbot_daily_total_metric");

                    b.ToTable("modbot_daily_total", (string)null);
                });

            modelBuilder.Entity("Modbot.Core.Data.Entities.DailyTotalsState", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ObservedThrough")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_through");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_modbot_daily_totals_state");

                    b.ToTable("modbot_daily_totals_state", null, t =>
                        {
                            t.HasCheckConstraint("ck_modbot_daily_totals_state_singleton", "id = 1");
                        });
                });

            modelBuilder.Entity("Modbot.Core.Data.Entities.EvidenceBlob", b =>
                {
                    b.Property<string>("Hash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash");

                    b.Property<short>("Backend")
                        .HasColumnType("smallint")
                        .HasColumnName("backend");

                    b.Property<long>("ByteSize")
                        .HasColumnType("bigint")
                        .HasColumnName("byte_size");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset?>("DestroyedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("destroyed_at");

                    b.Property<string>("DestroyedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("destroyed_by");

                    b.Property<string>("DestroyedReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("destroyed_reason");

                    b.Property<string>("FileName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("file_name");

                    b.Property<DateTimeOffset>("FirstStoredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_stored_at");

                    b.Property<short>("Origin")
                        .HasColumnType("smallint")
                        .HasColumnName("origin");

                    b.Property<string>("ReportId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("report_id");

                    b.Property<string>("UploaderId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("uploader_id");

                    b.HasKey("Hash")
                        .HasName("pk_modbot_evidence_blob");

                    b.HasIndex("ReportId")
                        .HasDatabaseName("ix_modbot_evidence_blob_report_id");

                    b.ToTable("modbot_evidence_blob", (string)null);
                });

            modelBuilder.Entity("Modbot.Core.Data.Entities.ModbotEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("ActorId")
                        .HasColumnType("text")
                        .HasColumnName("actor_id");

                    b.Property<short?>("ActorPlatform")
                        .HasColumnType("smallint")
                        .HasColumnName("actor_platform");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<string>("InstanceId")
                        .HasColumnType("text")
                        .HasColumnName("instance_id");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<DateTimeOffset?>("OccurredBefore")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_before");

                    b.Property<short>("Source")
                        .HasColumnType("smallint")
                        .HasColumnName("source");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_id");

                    b.Property<short>("SubjectPlatform")
                        .HasColumnType("smallint")
                        .HasColumnName("subject_platform");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("type");

                    b.Property<string>("TypeRaw")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("type_raw");

                    b.Property<string>("WorldId")
                        .HasColumnType("text")
                        .HasColumnName("world_id");

                    b.HasKey("Id", "OccurredAt")
                        .HasName("pk_modbot_event");

                    b.HasIndex("Data")
                        .HasDatabaseName("ix_modbot_event_data");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Data"), "gin");

                    b.HasIndex("Type", "OccurredAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_modbot_event_type");

                    b.HasIndex("ActorPlatform", "ActorId", "OccurredAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_modbot_event_actor");

                    b.HasIndex("SubjectPlatform", "SubjectId", "OccurredAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_modbot_event_subject");

                    b.HasIndex("InstanceId", "SubjectId", "Type", "OccurredAt")
                        .HasDatabaseName("ix_modbot_event_dedup");

                    b.ToTable("modbot_event", (string)null);
                });

            modelBuilder.Entity("Modbot.Core.Data.Entities.ModbotUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DiscordUserId")
                        .HasColumnType("text")
                        .HasColumnName("discord_user_id");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disabled");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<long>("Permissions")
                        .HasColumnType("bigint")
                        .HasColumnName("permissions");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("username");

                    b.Property<string>("UsernameNormalized")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("username_normalized");

                    b.HasKey("Id")
                        .HasName("pk_modbot_user");

                    b.HasIndex("UsernameNormalized")
                        .IsUnique()
                        .HasDatabaseName("ix_modbot_user_username_normalized");

                    b.ToTable("modbot_user", (string)null);
                });

            modelBuilder.Entity("Modbot.Core.Data.Entities.ProtectorKey", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<byte[]>("Key")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("key");

                    b.HasKey("Id")
                        .HasName("pk_protector_key");

                    b.ToTable("protector_key", null, t =>
                        {
                            t.HasCheckConstraint("ck_protector_key_singleton", "id = 1");
                        });
                });

            modelBuilder.Entity("Modbot.Core.Data.Entities.RateLimitBucket", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("Alerting")
                        .HasColumnType("boolean")
                        .HasColumnName("alerting");

                    b.Property<double>("BudgetMultiplier")
                        .HasColumnType("double precision")
                        .HasColumnName("budget_multiplier");

                    b.Property<double>("CeilingPerSecond")
                        .HasColumnType("double precision")
                        .HasColumnName("ceiling_per_second");

                    b.Property<int>("ConsecutiveProbeFailures")
                        .HasColumnType("integer")
                        .HasColumnName("consecutive_probe_failures");

                    b.Property<string>("EndpointClass")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("endpoint_class");

                    b.Property<double>("Fraction")
                        .HasColumnType("double precision")
                        .HasColumnName("fraction");

                    b.Property<DateTimeOffset>("LastAdaptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_adapted_at");

                    b.Property<DateTimeOffset?>("LastRateLimitedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_rate_limited_at");

                    b.Property<bool>("ProbeInFlight")
                        .HasColumnType("boolean")
                        .HasColumnName("probe_in_flight");

                    b.Property<int>("RateLimitHits")
                        .HasColumnType("integer")
                        .HasColumnName("rate_limit_hits");

                    b.Property<string>("ResourceId")
                        .HasColumnType("text")
                        .HasColumnName("resource_id");

                    b.Property<DateTimeOffset?>("StoppedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("stopped_until");

                    b.Property<double>("Tokens")
                        .HasColumnType("double precision")
                        .HasColumnName("tokens");

                    b.Property<DateTimeOffset>("TokensAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tokens_at");

                    b.HasKey("Name")
                        .HasName("pk_rate_limit_bucket");

                    b.HasIndex("StoppedUntil")
                        .HasDatabaseName("ix_rate_limit_bucket_stopped");

                    b.ToTable("rate_limit_bucket", (string)null);
                });

            modelBuilder.Entity("Modbot.Core.Data.Entities.Settings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("AuditLogBacklogOffset")
                        .HasColumnType("integer")
                        .HasColumnName("audit_log_backlog_offset");

                    b.Property<bool>("AuditLogCatchUpComplete")
                        .HasColumnType("boolean")
                        .HasColumnName("audit_log_catch_up_complete");

                    b.Property<int>("AuditLogCatchUpOffset")
                        .HasColumnType("integer")
                        .HasColumnName("audit_log_catch_up_offset");

                    b.Property<int>("AuditLogCatchUpVersion")
                        .HasColumnType("integer")
                        .HasColumnName("audit_log_catch_up_version");

                    b.Property<DateTimeOffset?>("AuditLogPolledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_log_polled_at");

                    b.Property<DateTimeOffset?>("AuditLogSyncedThrough")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_log_synced_through");

                    b.Property<DateTimeOffset?>("ConnectionCheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("connection_checked_at");

                    b.Property<int>("DedupWindowSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("dedup_window_seconds");

                    b.Property<string>("DiscordBotTokenEncrypted")
                        .HasColumnType("text")
                        .HasColumnName("discord_bot_token_encrypted");

                    b.Property<string>("DiscordGuildId")
                        .HasColumnType("text")
                        .HasColumnName("discord_guild_id");

                    b.Property<short>("EvidenceBackend")
                        .HasColumnType("smallint")
                        .HasColumnName("evidence_backend");

                    b.Property<bool>("EvidenceDirectDeliveryEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("evidence_direct_delivery_enabled");

                    b.Property<bool>("EvidenceDiskAcknowledged")
                        .HasColumnType("boolean")
                        .HasColumnName("evidence_disk_acknowledged");

                    b.Property<DateTimeOffset?>("EvidenceDiskAcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("evidence_disk_acknowledged_at");

                    b.Property<string>("EvidenceDiskAcknowledgedBy")
                        .HasColumnType("text")
                        .HasColumnName("evidence_disk_acknowledged_by");

                    b.Property<string>("EvidenceDiskWarningShown")
                        .HasColumnType("text")
                        .HasColumnName("evidence_disk_warning_shown");

                    b.Property<long>("EvidenceMaxDeploymentBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("evidence_max_deployment_bytes");

                    b.Property<long>("EvidenceMaxFileBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("evidence_max_file_bytes");

                    b.Property<long>("EvidenceMaxReportBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("evidence_max_report_bytes");

                    b.Property<string>("EvidenceRoot")
                        .HasColumnType("text")
                        .HasColumnName("evidence_root");

                    b.Property<string>("EvidenceS3AccessKeyId")
                        .HasColumnType("text")
                        .HasColumnName("evidence_s3access_key_id");

                    b.Property<string>("EvidenceS3Bucket")
                        .HasColumnType("text")
                        .HasColumnName("evidence_s3bucket");

                    b.Property<string>("EvidenceS3Endpoint")
                        .HasColumnType("text")
                        .HasColumnName("evidence_s3endpoint");

                    b.Property<string>("EvidenceS3Prefix")
                        .HasColumnType("text")
                        .HasColumnName("evidence_s3prefix");

                    b.Property<string>("EvidenceS3Region")
                        .HasColumnType("text")
                        .HasColumnName("evidence_s3region");

                    b.Property<string>("EvidenceS3SecretAccessKeyEncrypted")
                        .HasColumnType("text")
                        .HasColumnName("evidence_s3secret_access_key_encrypted");

                    b.Property<bool>("EvidenceS3UsePathStyle")
                        .HasColumnType("boolean")
                        .HasColumnName("evidence_s3use_path_style");

                    b.Property<Guid?>("EvidenceStoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("evidence_store_id");

                    b.Property<DateTimeOffset?>("GroupInfoPolledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("group_info_polled_at");

                    b.Property<string>("GroupInfoSnapshot")
                        .HasColumnType("text")
                        .HasColumnName("group_info_snapshot");

                    b.Property<string>("ManagedGroupId")
                        .HasColumnType("text")
                        .HasColumnName("managed_group_id");

                    b.Property<string>("ManagedGroupName")
                        .HasColumnType("text")
                        .HasColumnName("managed_group_name");

                    b.Property<int>("ModerationFactRetentionDays")
                        .HasColumnType("integer")
                        .HasColumnName("moderation_fact_retention_days");

                    b.Property<bool>("OnboardingComplete")
                        .HasColumnType("boolean")
                        .HasColumnName("onboarding_complete");

                    b.Property<int>("PresenceFactRetentionDays")
                        .HasColumnType("integer")
                        .HasColumnName("presence_fact_retention_days");

                    b.Property<string>("ProxyPasswordEncrypted")
                        .HasColumnType("text")
                        .HasColumnName("proxy_password_encrypted");

                    b.Property<string>("ProxyUrl")
                        .HasColumnType("text")
                        .HasColumnName("proxy_url");

                    b.Property<string>("ProxyUsername")
                        .HasColumnType("text")
                        .HasColumnName("proxy_username");

                    b.Property<bool>("RequireModerationClassification")
                        .HasColumnType("boolean")
                        .HasColumnName("require_moderation_classification");

                    b.Property<string>("SmtpFromAddress")
                        .HasColumnType("text")
                        .HasColumnName("smtp_from_address");

                    b.Property<string>("SmtpHost")
                        .HasColumnType("text")
                        .HasColumnName("smtp_host");

                    b.Property<string>("SmtpPasswordEncrypted")
                        .HasColumnType("text")
                        .HasColumnName("smtp_password_encrypted");

                    b.Property<int?>("SmtpPort")
                        .HasColumnType("integer")
                        .HasColumnName("smtp_port");

                    b.Property<bool>("SmtpUseTls")
                        .HasColumnType("boolean")
                        .HasColumnName("smtp_use_tls");

                    b.Property<string>("SmtpUsername")
                        .HasColumnType("text")
                        .HasColumnName("smtp_username");

                    b.Property<string>("SyncPacing")
                        .HasColumnType("jsonb")
                        .HasColumnName("sync_pacing");

                    b.Property<long>("UserProfileEventsReadThrough")
                        .HasColumnType("bigint")
                        .HasColumnName("user_profile_events_read_through");

                    b.Property<DateTimeOffset?>("UserProfilePolledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("user_profile_polled_at");

                    b.Property<string>("VRChatAuthCookieEncrypted")
                        .HasColumnType("text")
                        .HasColumnName("vr_chat_auth_cookie_encrypted");

                    b.Property<string>("VRChatDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("vr_chat_display_name");

                    b.Property<string>("VRChatPasswordEncrypted")
                        .HasColumnType("text")
                        .HasColumnName("vr_chat_password_encrypted");

                    b.Property<string>("VRChatTotpSecretEncrypted")
                        .HasColumnType("text")
                        .HasColumnName("vr_chat_totp_secret_encrypted");

                    b.Property<string>("VRChatUsername")
                        .HasColumnType("text")
                        .HasColumnName("vr_chat_username");

                    b.Property<DateTimeOffset?>("VRChatVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vr_chat_verified_at");

                    b.HasKey("Id")
                        .HasName("pk_settings");

                    b.ToTable("settings", null, t =>
                        {
                            t.HasCheckConstraint("ck_settings_singleton", "id = 1");
                        });
                });

            modelBuilder.Entity("Modbot.Core.Data.Entities.VRChatUser", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("AgeVerificationStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("age_verification_status");

                    b.Property<bool?>("AgeVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("age_verified");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<string>("CurrentAvatarImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("current_avatar_image_url");

                    b.Property<string>("CurrentAvatarThumbnailImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("current_avatar_thumbnail_image_url");

                    b.Property<DateOnly?>("DateJoined")
                        .HasColumnType("date")
                        .HasColumnName("date_joined");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<bool>("Is18PlusVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_18_plus_verified");

                    b.Property<DateTimeOffset?>("Is18PlusVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("is_18_plus_verified_at");

                    b.Property<Guid?>("Is18PlusVerifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("is_18_plus_verified_by_user_id");

                    b.Property<string>("Is18PlusVerifiedSource")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("is_18_plus_verified_source");

                    b.Property<string>("LastPlatform")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("last_platform");

                    b.Property<DateTimeOffset?>("LastRefreshedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_refreshed_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<DateTimeOffset?>("NotFoundAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("not_found_at");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text")
                        .HasColumnName("profile_picture_url");

                    b.Property<string>("Pronouns")
                        .HasColumnType("text")
                        .HasColumnName("pronouns");

                    b.Property<string>("RawProfile")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_profile");

                    b.Property<string>("RefreshError")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("refresh_error");

                    b.Property<DateTimeOffset?>("RefreshErrorAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_error_at");

                    b.Property<string>("Status")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("StatusDescription")
                        .HasColumnType("text")
                        .HasColumnName("status_description");

                    b.Property<string>("Tags")
                        .HasColumnType("jsonb")
                        .HasColumnName("tags");

                    b.HasKey("UserId")
                        .HasName("pk_vrchat_user");

                    b.HasIndex("LastRefreshedAt")
                        .HasDatabaseName("ix_vrchat_user_last_refreshed");

                    b.HasIndex("LastSeenAt")
                        .HasDatabaseName("ix_vrchat_user_last_seen");

                    b.ToTable("vrchat_user", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
