// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modbot.Core.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modbot.Core.Data.Migrations
{
    [DbContext(typeof(ModbotContext))]
    [Migration("20260914004239_AddInstanceAnnouncements")]
    partial class AddInstanceAnnouncements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .HasColumnType("text")
                        .HasColumnName("xml");

                    b.HasKey("Id")
                        .HasName("pk_data_protection_keys");

                    b.ToTable("data_protection_keys", (string)null);
                });

            modelBuilder.Entity("Modbot.Core.Data.Entities.BanReason", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("label");

                    b.Property<bool>("NeedsWrittenReason")
                        .HasColumnType("boolean")
                        .HasColumnName("needs_written_reason");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_ban_reason");

                    b.HasIndex("SortOrder")
                        .HasDatabaseName("ix_ban_reason_order");

                    b.ToTable("ban_reason", (string)null);
                });

            modelBuilder.Entity("Modbot.Core.Data.Entities.CaseFile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuditEntryId")
                        .HasColumnType("text")
                        .HasColumnName("audit_entry_id");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user_id");

                    b.Property<string>("AuthorUsername")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("author_username");

                    b.Property<long?>("BanFactId")
                        .HasColumnType("bigint")
                        .HasColumnName("ban_fact_id");

                    b.Property<string>("BanListEntryAtBan")
                        .HasColumnType("jsonb")
                        .HasColumnName("ban_list_entry_at_ban");

                    b.Property<DateTimeOffset?>("BannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("banned_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GroupId")
                        .HasColumnType("text")
                        .HasColumnName("group_id");

                    b.Property<string>("MembershipAtBan")
                        .HasColumnType("jsonb")
                        .HasColumnName("membership_at_ban");

                    b.Property<string>("ProfileAtBan")
                        .HasColumnType("jsonb")
                        .HasColumnName("profile_at_ban");

                    b.Property<DateTimeOffset?>("ProfileRefreshedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("profile_refreshed_at");

                    b.Property<string>("ReasonIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("reason_ids");

                    b.Property<DateTimeOffset?>("SnapshotRecapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("snapshot_recaptured_at");

                    b.Property<DateTimeOffset>("SnapshotTakenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("snapshot_taken_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<string>("UpdatedByUsername")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("updated_by_username");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset?>("WithdrawnAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("withdrawn_at");

                    b.Property<Guid?>("WithdrawnByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("withdrawn_by_user_id");

                    b.Property<string>("WithdrawnByUsername")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("withdrawn_by_username");

                    b.Property<string>("WithdrawnNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("withdrawn_note");

                    b.Property<string>("WrittenReason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("written_reason");

                    b.HasKey("Id")
                        .HasName("pk_case_file");

                    b.HasIndex("AuditEntryId")
                        .HasDatabaseName("ix_case_file_audit_entry")
                        .HasFilter("audit_entry_id IS NOT NULL");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_case_file_created");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_case_file_user");

                    b.ToTable("case_file", (string)null);
                });

            modelBuilder.Entity("Modbot.Core.Data.Entities.ClientDeviceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClientVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("client_version");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<Guid>("IssuedToUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("issued_to_user_id");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("platform");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_client_device");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_client_device_token_hash");

                    b.ToTable("client_device", (string)null);
                });

            modelBuilder.Entity("Modbot.Core.Data.Entities.ClientPairingCodeRecord", b =>
                {
                    b.Property<string>("CodeHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<Guid>("IssuedToUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("issued_to_user_id");

                    b.Property<DateTimeOffset?>("RedeemedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("redeemed_at");

                    b.HasKey("CodeHash")
                        .HasName("pk_client_pairing_code");

                    b.ToTable("client_pairing_code", (string)null);
                });

            modelBuilder.Entity("Modbot.Core.Data.Entities.DailyTotal", b =>
                {
                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<string>("Metric")
                        .HasColumnType("text")
                        .HasColumnName("metric");

                    b.Property<string>("Dimension")
                        .HasColumnType("text")
                        .HasColumnName("dimension");

                    b.Property<short>("Origin")
                        .HasColumnType("smallint")
                        .HasColumnName("origin");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric")
                        .HasColumnName("value");

                    b.HasKey("Day", "Metric", "Dimension")
                        .HasName("pk_modbot_daily_total");

                    b.HasIndex("Metric", "Day")
                        .HasDatabaseName("ix_modbot_daily_total_metric");

                    b.ToTable("modbot_daily_total", (string)null);
                });

            modelBuilder.Entity("Modbot.Core.Data.Entities.DailyTotalsState", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ObservedThrough")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_through");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_modbot_daily_totals_state");

                    b.ToTable("modbot_daily_totals_state", null, t =>
                        {
                            t.HasCheckConstraint("ck_modbot_daily_totals_state_singleton", "id = 1");
                        });
                });

            modelBuilder.Entity("Modbot.Core.Data.Entities.EvidenceBlob", b =>
                {
                    b.Property<string>("Hash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash");

                    b.Property<short>("Backend")
                        .HasColumnType("smallint")
                        .HasColumnName("backend");

                    b.Property<long>("ByteSize")
                        .HasColumnType("bigint")
                        .HasColumnName("byte_size");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset?>("DestroyedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("destroyed_at");

                    b.Property<string>("DestroyedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("destroyed_by");

                    b.Property<string>("DestroyedReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("destroyed_reason");

                    b.Property<string>("FileName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("file_name");

                    b.Property<DateTimeOffset>("FirstStoredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_stored_at");

                    b.Property<short>("Origin")
                        .HasColumnType("smallint")
                        .HasColumnName("origin");

                    b.Property<string>("ReportId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("report_id");

                    b.Property<string>("UploaderId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("uploader_id");

                    b.HasKey("Hash")
                        .HasName("pk_modbot_evidence_blob");

                    b.HasIndex("ReportId")
                        .HasDatabaseName("ix_modbot_evidence_blob_report_id");

                    b.ToTable("modbot_evidence_blob", (string)null);
                });

            modelBuilder.Entity("Modbot.Core.Data.Entities.GroupBan", b =>
                {
                    b.Property<string>("GroupId")
                        .HasColumnType("text")
                        .HasColumnName("group_id");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset?>("BannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("banned_at");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<DateTimeOffset?>("LiftedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lifted_at");

                    b.Property<string>("Raw")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw");

                    b.Property<string>("WaitingFacts")
                        .HasColumnType("jsonb")
                        .HasColumnName("waiting_facts");

                    b.HasKey("GroupId", "UserId")
                        .HasName("pk_group_ban");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_group_ban_waiting")
                        .HasFilter("waiting_facts IS NOT NULL");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_group_ban_user");

                    b.HasIndex("GroupId", "LiftedAt", "BannedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_group_ban_current");

                    b.ToTable("group_ban", (string)null);
                });

            modelBuilder.Entity("Modbot.Core.Data.Entities.GroupMember", b =>
                {
                    b.Property<string>("GroupId")
                        .HasColumnType("text")
                        .HasColumnName("group_id");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<bool>("IsRepresenting")
                        .HasColumnType("boolean")
                        .HasColumnName("is_representing");

                    b.Property<DateTimeOffset?>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<DateTimeOffset?>("LeftAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("left_at");

                    b.Property<string>("ManagerNotes")
                        .HasColumnType("text")
                        .HasColumnName("manager_notes");

                    b.Property<string>("MembershipId")
                        .HasColumnType("text")
                        .HasColumnName("membership_id");

                    b.Property<string>("MembershipStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("membership_status");

                    b.Property<string>("Raw")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("roles");

                    b.Property<string>("Visibility")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("visibility");

                    b.Property<string>("WaitingFacts")
                        .HasColumnType("jsonb")
                        .HasColumnName("waiting_facts");

                    b.HasKey("GroupId", "UserId")
                        .HasName("pk_group_member");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_group_member_waiting")
                        .HasFilter("waiting_facts IS NOT NULL");

                    b.HasIndex("Roles")
                        .HasDatabaseName("ix_group_member_roles");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Roles"), "gin");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_group_member_user");

                    b.HasIndex("GroupId", "LeftAt", "JoinedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_group_member_current");

                    b.ToTable("group_member", (string)null);
                });

            modelBuilder.Entity("Modbot.Core.Data.Entities.ModbotEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("ActorId")
                        .HasColumnType("text")
                        .HasColumnName("actor_id");

                    b.Property<short?>("ActorPlatform")
                        .HasColumnType("smallint")
                        .HasColumnName("actor_platform");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<string>("InstanceId")
                        .HasColumnType("text")
                        .HasColumnName("instance_id");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<DateTimeOffset?>("OccurredBefore")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_before");

                    b.Property<short>("Source")
                        .HasColumnType("smallint")
                        .HasColumnName("source");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_id");

                    b.Property<short>("SubjectPlatform")
                        .HasColumnType("smallint")
                        .HasColumnName("subject_platform");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("type");

                    b.Property<string>("TypeRaw")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("type_raw");

                    b.Property<string>("WorldId")
                        .HasColumnType("text")
                        .HasColumnName("world_id");

                    b.HasKey("Id", "OccurredAt")
                        .HasName("pk_modbot_event");

                    b.HasIndex("Data")
                        .HasDatabaseName("ix_modbot_event_data");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Data"), "gin");

                    b.HasIndex("Type", "OccurredAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_modbot_event_type");

                    b.HasIndex("ActorPlatform", "ActorId", "OccurredAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_modbot_event_actor");

                    b.HasIndex("SubjectPlatform", "SubjectId", "OccurredAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_modbot_event_subject");

                    b.HasIndex("InstanceId", "SubjectId", "Type", "OccurredAt")
                        .HasDatabaseName("ix_modbot_event_dedup");

                    b.ToTable("modbot_event", (string)null);
                });

            modelBuilder.Entity("Modbot.Core.Data.Entities.ModbotRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("boolean")
                        .HasColumnName("is_built_in");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<string>("NameNormalized")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name_normalized");

                    b.Property<long>("Permissions")
                        .HasColumnType("bigint")
                        .HasColumnName("permissions");

                    b.HasKey("Id")
                        .HasName("pk_modbot_role");

                    b.HasIndex("NameNormalized")
                        .IsUnique()
                        .HasDatabaseName("ix_modbot_role_name_normalized");

                    b.ToTable("modbot_role", (string)null);
                });

            modelBuilder.Entity("Modbot.Core.Data.Entities.ModbotUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DiscordUserId")
                        .HasColumnType("text")
                        .HasColumnName("discord_user_id");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disabled");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset?>("SessionsValidAfter")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sessions_valid_after");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("username");

                    b.Property<string>("UsernameNormalized")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("username_normalized");

                    b.Property<string>("VRChatDisplayName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("vr_chat_display_name");

                    b.Property<int>("VRChatLinkChecks")
                        .HasColumnType("integer")
                        .HasColumnName("vr_chat_link_checks");

                    b.Property<string>("VRChatLinkCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("vr_chat_link_code");

                    b.Property<DateTimeOffset?>("VRChatLinkCodeExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vr_chat_link_code_expires_at");

                    b.Property<DateTimeOffset?>("VRChatLinkLastCheckAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vr_chat_link_last_check_at");

                    b.Property<string>("VRChatLinkPendingUserId")
                        .HasColumnType("text")
                        .HasColumnName("vr_chat_link_pending_user_id");

                    b.Property<DateTimeOffset?>("VRChatLinkedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vr_chat_linked_at");

                    b.Property<string>("VRChatUserId")
                        .HasColumnType("text")
                        .HasColumnName("vr_chat_user_id");

                    b.HasKey("Id")
                        .HasName("pk_modbot_user");

                    b.HasIndex("UsernameNormalized")
                        .IsUnique()
                        .HasDatabaseName("ix_modbot_user_username_normalized");

                    b.HasIndex("VRChatUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_modbot_user_vr_chat_user_id");

                    b.ToTable("modbot_user", (string)null);
                });

            modelBuilder.Entity("Modbot.Core.Data.Entities.ModbotUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_modbot_user_role");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_modbot_user_role_role_id");

                    b.ToTable("modbot_user_role", (string)null);
                });

            modelBuilder.Entity("Modbot.Core.Data.Entities.ModeratorBaseline", b =>
                {
                    b.Property<short>("Platform")
                        .HasColumnType("smallint")
                        .HasColumnName("platform");

                    b.Property<string>("ModeratorId")
                        .HasColumnType("text")
                        .HasColumnName("moderator_id");

                    b.Property<decimal>("Actions")
                        .HasColumnType("numeric")
                        .HasColumnName("actions");

                    b.Property<decimal>("ActionsPerActiveDay")
                        .HasColumnType("numeric")
                        .HasColumnName("actions_per_active_day");

                    b.Property<int>("ActiveDays")
                        .HasColumnType("integer")
                        .HasColumnName("active_days");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at");

                    b.Property<DateOnly?>("FirstDay")
                        .HasColumnType("date")
                        .HasColumnName("first_day");

                    b.Property<DateOnly?>("LastDay")
                        .HasColumnType("date")
                        .HasColumnName("last_day");

                    b.HasKey("Platform", "ModeratorId")
                        .HasName("pk_modbot_moderator_baseline");

                    b.ToTable("modbot_moderator_baseline", (string)null);
                });

            modelBuilder.Entity("Modbot.Core.Data.Entities.OneTimeLink", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<short>("Kind")
                        .HasColumnType("smallint")
                        .HasColumnName("kind");

                    b.PrimitiveCollection<string>("RoleIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("role_ids");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_modbot_one_time_link");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_modbot_one_time_link_created_by_user_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_modbot_one_time_link_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_modbot_one_time_link_user_id");

                    b.ToTable("modbot_one_time_link", (string)null);
                });

            modelBuilder.Entity("Modbot.Core.Data.Entities.ProtectorKey", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<byte[]>("Key")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("key");

                    b.HasKey("Id")
                        .HasName("pk_protector_key");

                    b.ToTable("protector_key", null, t =>
                        {
                            t.HasCheckConstraint("ck_protector_key_singleton", "id = 1");
                        });
                });

            modelBuilder.Entity("Modbot.Core.Data.Entities.RateLimitBucket", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("Alerting")
                        .HasColumnType("boolean")
                        .HasColumnName("alerting");

                    b.Property<double>("BudgetMultiplier")
                        .HasColumnType("double precision")
                        .HasColumnName("budget_multiplier");

                    b.Property<double>("CeilingPerSecond")
                        .HasColumnType("double precision")
                        .HasColumnName("ceiling_per_second");

                    b.Property<int>("ConsecutiveProbeFailures")
                        .HasColumnType("integer")
                        .HasColumnName("consecutive_probe_failures");

                    b.Property<string>("EndpointClass")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("endpoint_class");

                    b.Property<double>("Fraction")
                        .HasColumnType("double precision")
                        .HasColumnName("fraction");

                    b.Property<DateTimeOffset>("LastAdaptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_adapted_at");

                    b.Property<DateTimeOffset?>("LastRateLimitedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_rate_limited_at");

                    b.Property<bool>("ProbeInFlight")
                        .HasColumnType("boolean")
                        .HasColumnName("probe_in_flight");

                    b.Property<int>("RateLimitHits")
                        .HasColumnType("integer")
                        .HasColumnName("rate_limit_hits");

                    b.Property<string>("ResourceId")
                        .HasColumnType("text")
                        .HasColumnName("resource_id");

                    b.Property<DateTimeOffset?>("StoppedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("stopped_until");

                    b.Property<double>("Tokens")
                        .HasColumnType("double precision")
                        .HasColumnName("tokens");

                    b.Property<DateTimeOffset>("TokensAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tokens_at");

                    b.HasKey("Name")
                        .HasName("pk_rate_limit_bucket");

                    b.HasIndex("StoppedUntil")
                        .HasDatabaseName("ix_rate_limit_bucket_stopped");

                    b.ToTable("rate_limit_bucket", (string)null);
                });

            modelBuilder.Entity("Modbot.Core.Data.Entities.RepeatOffender", b =>
                {
                    b.Property<short>("SubjectPlatform")
                        .HasColumnType("smallint")
                        .HasColumnName("subject_platform");

                    b.Property<string>("SubjectId")
                        .HasColumnType("text")
                        .HasColumnName("subject_id");

                    b.Property<int>("Actions")
                        .HasColumnType("integer")
                        .HasColumnName("actions");

                    b.Property<int>("ActionsLast30Days")
                        .HasColumnType("integer")
                        .HasColumnName("actions_last_30_days");

                    b.Property<int>("ActionsLast90Days")
                        .HasColumnType("integer")
                        .HasColumnName("actions_last_90_days");

                    b.Property<int>("Bans")
                        .HasColumnType("integer")
                        .HasColumnName("bans");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at");

                    b.Property<DateTimeOffset?>("CountsChangeAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("counts_change_at");

                    b.Property<DateTimeOffset>("FirstActionAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_action_at");

                    b.Property<int>("InstanceKicks")
                        .HasColumnType("integer")
                        .HasColumnName("instance_kicks");

                    b.Property<DateTimeOffset>("LastActionAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_action_at");

                    b.Property<string>("LastActionType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("last_action_type");

                    b.Property<string>("LastActorId")
                        .HasColumnType("text")
                        .HasColumnName("last_actor_id");

                    b.Property<int>("Moderators")
                        .HasColumnType("integer")
                        .HasColumnName("moderators");

                    b.Property<int>("ModeratorsLast90Days")
                        .HasColumnType("integer")
                        .HasColumnName("moderators_last_90_days");

                    b.Property<int>("Rejections")
                        .HasColumnType("integer")
                        .HasColumnName("rejections");

                    b.Property<int>("Removals")
                        .HasColumnType("integer")
                        .HasColumnName("removals");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<int>("Unbans")
                        .HasColumnType("integer")
                        .HasColumnName("unbans");

                    b.Property<int>("Warns")
                        .HasColumnType("integer")
                        .HasColumnName("warns");

                    b.HasKey("SubjectPlatform", "SubjectId")
                        .HasName("pk_modbot_repeat_offender");

                    b.HasIndex("CountsChangeAt")
                        .HasDatabaseName("ix_modbot_repeat_offender_counts_change");

                    b.HasIndex("LastActionAt")
                        .IsDescending()
                        .HasDatabaseName("ix_modbot_repeat_offender_last_action");

                    b.ToTable("modbot_repeat_offender", (string)null);
                });

            modelBuilder.Entity("Modbot.Core.Data.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("about");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<Guid?>("ClosedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("closed_by_user_id");

                    b.Property<string>("ClosedByUsername")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("closed_by_username");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("evidence");

                    b.Property<string>("ModeratorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("moderator_id");

                    b.Property<short>("ModeratorPlatform")
                        .HasColumnType("smallint")
                        .HasColumnName("moderator_platform");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<string>("Signal")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("signal");

                    b.Property<short>("State")
                        .HasColumnType("smallint")
                        .HasColumnName("state");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset>("WindowEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_end");

                    b.Property<DateTimeOffset>("WindowStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_start");

                    b.HasKey("Id")
                        .HasName("pk_modbot_review");

                    b.HasIndex("State", "OpenedAt")
                        .HasDatabaseName("ix_modbot_review_state");

                    b.HasIndex("ModeratorPlatform", "ModeratorId", "Signal", "About")
                        .IsUnique()
                        .HasDatabaseName("ux_modbot_review_open")
                        .HasFilter("state = 1");

                    b.HasIndex("ModeratorPlatform", "ModeratorId", "Signal", "About", "WindowEnd")
                        .HasDatabaseName("ix_modbot_review_key");

                    b.ToTable("modbot_review", (string)null);
                });

            modelBuilder.Entity("Modbot.Core.Data.Entities.ReviewRunState", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ObservedThrough")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_through");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_modbot_review_run_state");

                    b.ToTable("modbot_review_run_state", null, t =>
                        {
                            t.HasCheckConstraint("ck_modbot_review_run_state_singleton", "id = 1");
                        });
                });

            modelBuilder.Entity("Modbot.Core.Data.Entities.Settings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("AuditLogBacklogOffset")
                        .HasColumnType("integer")
                        .HasColumnName("audit_log_backlog_offset");

                    b.Property<bool>("AuditLogCatchUpComplete")
                        .HasColumnType("boolean")
                        .HasColumnName("audit_log_catch_up_complete");

                    b.Property<int>("AuditLogCatchUpOffset")
                        .HasColumnType("integer")
                        .HasColumnName("audit_log_catch_up_offset");

                    b.Property<int>("AuditLogCatchUpVersion")
                        .HasColumnType("integer")
                        .HasColumnName("audit_log_catch_up_version");

                    b.Property<DateTimeOffset?>("AuditLogPolledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_log_polled_at");

                    b.Property<DateTimeOffset?>("AuditLogSyncedThrough")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_log_synced_through");

                    b.Property<DateTimeOffset?>("BanSweepCompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ban_sweep_completed_at");

                    b.Property<int>("BanSweepCount")
                        .HasColumnType("integer")
                        .HasColumnName("ban_sweep_count");

                    b.Property<int>("BanSweepOffset")
                        .HasColumnType("integer")
                        .HasColumnName("ban_sweep_offset");

                    b.Property<DateTimeOffset?>("BanSweepPolledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ban_sweep_polled_at");

                    b.Property<DateTimeOffset?>("BanSweepPreviousStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ban_sweep_previous_started_at");

                    b.Property<int>("BanSweepSeenSoFar")
                        .HasColumnType("integer")
                        .HasColumnName("ban_sweep_seen_so_far");

                    b.Property<DateTimeOffset?>("BanSweepStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ban_sweep_started_at");

                    b.Property<DateTimeOffset?>("ConnectionCheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("connection_checked_at");

                    b.Property<int>("DedupWindowSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("dedup_window_seconds");

                    b.Property<string>("DiscordBotTokenEncrypted")
                        .HasColumnType("text")
                        .HasColumnName("discord_bot_token_encrypted");

                    b.Property<string>("DiscordGuildId")
                        .HasColumnType("text")
                        .HasColumnName("discord_guild_id");

                    b.Property<string>("DiscordInstanceChannelId")
                        .HasColumnType("text")
                        .HasColumnName("discord_instance_channel_id");

                    b.Property<string>("DiscordInstanceMessage")
                        .HasColumnType("text")
                        .HasColumnName("discord_instance_message");

                    b.Property<string>("DiscordLogChannelId")
                        .HasColumnType("text")
                        .HasColumnName("discord_log_channel_id");

                    b.Property<string>("DiscordLogEventTypes")
                        .HasColumnType("text")
                        .HasColumnName("discord_log_event_types");

                    b.Property<long?>("DiscordLogPostedThrough")
                        .HasColumnType("bigint")
                        .HasColumnName("discord_log_posted_through");

                    b.Property<short>("EvidenceBackend")
                        .HasColumnType("smallint")
                        .HasColumnName("evidence_backend");

                    b.Property<bool>("EvidenceDirectDeliveryEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("evidence_direct_delivery_enabled");

                    b.Property<bool>("EvidenceDiskAcknowledged")
                        .HasColumnType("boolean")
                        .HasColumnName("evidence_disk_acknowledged");

                    b.Property<DateTimeOffset?>("EvidenceDiskAcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("evidence_disk_acknowledged_at");

                    b.Property<string>("EvidenceDiskAcknowledgedBy")
                        .HasColumnType("text")
                        .HasColumnName("evidence_disk_acknowledged_by");

                    b.Property<string>("EvidenceDiskWarningShown")
                        .HasColumnType("text")
                        .HasColumnName("evidence_disk_warning_shown");

                    b.Property<long>("EvidenceMaxDeploymentBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("evidence_max_deployment_bytes");

                    b.Property<long>("EvidenceMaxFileBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("evidence_max_file_bytes");

                    b.Property<long>("EvidenceMaxReportBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("evidence_max_report_bytes");

                    b.Property<string>("EvidenceRoot")
                        .HasColumnType("text")
                        .HasColumnName("evidence_root");

                    b.Property<string>("EvidenceS3AccessKeyId")
                        .HasColumnType("text")
                        .HasColumnName("evidence_s3access_key_id");

                    b.Property<string>("EvidenceS3Bucket")
                        .HasColumnType("text")
                        .HasColumnName("evidence_s3bucket");

                    b.Property<string>("EvidenceS3Endpoint")
                        .HasColumnType("text")
                        .HasColumnName("evidence_s3endpoint");

                    b.Property<string>("EvidenceS3Prefix")
                        .HasColumnType("text")
                        .HasColumnName("evidence_s3prefix");

                    b.Property<string>("EvidenceS3Region")
                        .HasColumnType("text")
                        .HasColumnName("evidence_s3region");

                    b.Property<string>("EvidenceS3SecretAccessKeyEncrypted")
                        .HasColumnType("text")
                        .HasColumnName("evidence_s3secret_access_key_encrypted");

                    b.Property<bool>("EvidenceS3UsePathStyle")
                        .HasColumnType("boolean")
                        .HasColumnName("evidence_s3use_path_style");

                    b.Property<Guid?>("EvidenceStoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("evidence_store_id");

                    b.Property<DateTimeOffset?>("GroupInfoPolledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("group_info_polled_at");

                    b.Property<string>("GroupInfoSnapshot")
                        .HasColumnType("text")
                        .HasColumnName("group_info_snapshot");

                    b.Property<DateTimeOffset?>("GroupInstancesPolledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("group_instances_polled_at");

                    b.Property<string>("ManagedGroupId")
                        .HasColumnType("text")
                        .HasColumnName("managed_group_id");

                    b.Property<string>("ManagedGroupName")
                        .HasColumnType("text")
                        .HasColumnName("managed_group_name");

                    b.Property<DateTimeOffset?>("MemberSweepCompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("member_sweep_completed_at");

                    b.Property<int>("MemberSweepCount")
                        .HasColumnType("integer")
                        .HasColumnName("member_sweep_count");

                    b.Property<int>("MemberSweepOffset")
                        .HasColumnType("integer")
                        .HasColumnName("member_sweep_offset");

                    b.Property<DateTimeOffset?>("MemberSweepPolledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("member_sweep_polled_at");

                    b.Property<DateTimeOffset?>("MemberSweepPreviousStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("member_sweep_previous_started_at");

                    b.Property<int>("MemberSweepSeenSoFar")
                        .HasColumnType("integer")
                        .HasColumnName("member_sweep_seen_so_far");

                    b.Property<DateTimeOffset?>("MemberSweepStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("member_sweep_started_at");

                    b.Property<int>("ModerationFactRetentionDays")
                        .HasColumnType("integer")
                        .HasColumnName("moderation_fact_retention_days");

                    b.Property<bool>("OnboardingComplete")
                        .HasColumnType("boolean")
                        .HasColumnName("onboarding_complete");

                    b.Property<int>("PresenceFactRetentionDays")
                        .HasColumnType("integer")
                        .HasColumnName("presence_fact_retention_days");

                    b.Property<string>("ProxyPasswordEncrypted")
                        .HasColumnType("text")
                        .HasColumnName("proxy_password_encrypted");

                    b.Property<string>("ProxyUrl")
                        .HasColumnType("text")
                        .HasColumnName("proxy_url");

                    b.Property<string>("ProxyUsername")
                        .HasColumnType("text")
                        .HasColumnName("proxy_username");

                    b.Property<string>("PublicAddress")
                        .HasColumnType("text")
                        .HasColumnName("public_address");

                    b.Property<bool>("RequireModerationClassification")
                        .HasColumnType("boolean")
                        .HasColumnName("require_moderation_classification");

                    b.Property<string>("ReviewThresholds")
                        .HasColumnType("jsonb")
                        .HasColumnName("review_thresholds");

                    b.Property<string>("SmtpFromAddress")
                        .HasColumnType("text")
                        .HasColumnName("smtp_from_address");

                    b.Property<string>("SmtpHost")
                        .HasColumnType("text")
                        .HasColumnName("smtp_host");

                    b.Property<string>("SmtpPasswordEncrypted")
                        .HasColumnType("text")
                        .HasColumnName("smtp_password_encrypted");

                    b.Property<int?>("SmtpPort")
                        .HasColumnType("integer")
                        .HasColumnName("smtp_port");

                    b.Property<bool>("SmtpUseTls")
                        .HasColumnType("boolean")
                        .HasColumnName("smtp_use_tls");

                    b.Property<string>("SmtpUsername")
                        .HasColumnType("text")
                        .HasColumnName("smtp_username");

                    b.Property<string>("SyncPacing")
                        .HasColumnType("jsonb")
                        .HasColumnName("sync_pacing");

                    b.Property<long>("UserProfileEventsReadThrough")
                        .HasColumnType("bigint")
                        .HasColumnName("user_profile_events_read_through");

                    b.Property<DateTimeOffset?>("UserProfilePolledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("user_profile_polled_at");

                    b.Property<string>("VRChatAuthCookieEncrypted")
                        .HasColumnType("text")
                        .HasColumnName("vr_chat_auth_cookie_encrypted");

                    b.Property<string>("VRChatDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("vr_chat_display_name");

                    b.Property<string>("VRChatPasswordEncrypted")
                        .HasColumnType("text")
                        .HasColumnName("vr_chat_password_encrypted");

                    b.Property<string>("VRChatTotpSecretEncrypted")
                        .HasColumnType("text")
                        .HasColumnName("vr_chat_totp_secret_encrypted");

                    b.Property<string>("VRChatUsername")
                        .HasColumnType("text")
                        .HasColumnName("vr_chat_username");

                    b.Property<DateTimeOffset?>("VRChatVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vr_chat_verified_at");

                    b.Property<DateTimeOffset?>("WorldSweepPolledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("world_sweep_polled_at");

                    b.HasKey("Id")
                        .HasName("pk_settings");

                    b.ToTable("settings", null, t =>
                        {
                            t.HasCheckConstraint("ck_settings_singleton", "id = 1");
                        });
                });

            modelBuilder.Entity("Modbot.Core.Data.Entities.VRChatInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnnouncementChannelId")
                        .HasColumnType("text")
                        .HasColumnName("announcement_channel_id");

                    b.Property<bool>("AnnouncementFinished")
                        .HasColumnType("boolean")
                        .HasColumnName("announcement_finished");

                    b.Property<string>("AnnouncementMessageId")
                        .HasColumnType("text")
                        .HasColumnName("announcement_message_id");

                    b.Property<DateTimeOffset?>("AnnouncementUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("announcement_updated_at");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<string>("ClosedBy")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("closed_by");

                    b.Property<string>("GroupAccessType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("group_access_type");

                    b.Property<string>("GroupId")
                        .HasColumnType("text")
                        .HasColumnName("group_id");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<int?>("LastUserCount")
                        .HasColumnType("integer")
                        .HasColumnName("last_user_count");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<int?>("PeakUserCount")
                        .HasColumnType("integer")
                        .HasColumnName("peak_user_count");

                    b.Property<string>("Region")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("region");

                    b.Property<bool>("SeenInGroupList")
                        .HasColumnType("boolean")
                        .HasColumnName("seen_in_group_list");

                    b.Property<string>("Type")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<string>("VRChatInstanceId")
                        .HasColumnType("text")
                        .HasColumnName("vr_chat_instance_id");

                    b.Property<string>("WorldId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_vrchat_instance");

                    b.HasIndex("AnnouncementUpdatedAt")
                        .HasDatabaseName("ix_vrchat_instance_announcing")
                        .HasFilter("announcement_finished = false");

                    b.HasIndex("GroupId", "OpenedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_vrchat_instance_group");

                    b.HasIndex("Location", "LastSeenAt")
                        .HasDatabaseName("ix_vrchat_instance_open")
                        .HasFilter("closed_at IS NULL");

                    b.HasIndex("WorldId", "OpenedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_vrchat_instance_world");

                    b.ToTable("vrchat_instance", (string)null);
                });

            modelBuilder.Entity("Modbot.Core.Data.Entities.VRChatUser", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("AgeVerificationStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("age_verification_status");

                    b.Property<bool?>("AgeVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("age_verified");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<string>("CurrentAvatarImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("current_avatar_image_url");

                    b.Property<string>("CurrentAvatarThumbnailImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("current_avatar_thumbnail_image_url");

                    b.Property<DateOnly?>("DateJoined")
                        .HasColumnType("date")
                        .HasColumnName("date_joined");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<bool>("Is18PlusVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_18_plus_verified");

                    b.Property<DateTimeOffset?>("Is18PlusVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("is_18_plus_verified_at");

                    b.Property<Guid?>("Is18PlusVerifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("is_18_plus_verified_by_user_id");

                    b.Property<string>("Is18PlusVerifiedSource")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("is_18_plus_verified_source");

                    b.Property<string>("LastPlatform")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("last_platform");

                    b.Property<DateTimeOffset?>("LastRefreshedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_refreshed_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<DateTimeOffset?>("NotFoundAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("not_found_at");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text")
                        .HasColumnName("profile_picture_url");

                    b.Property<string>("Pronouns")
                        .HasColumnType("text")
                        .HasColumnName("pronouns");

                    b.Property<string>("RawProfile")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_profile");

                    b.Property<string>("RefreshError")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("refresh_error");

                    b.Property<DateTimeOffset?>("RefreshErrorAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_error_at");

                    b.Property<string>("Status")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("StatusDescription")
                        .HasColumnType("text")
                        .HasColumnName("status_description");

                    b.Property<string>("Tags")
                        .HasColumnType("jsonb")
                        .HasColumnName("tags");

                    b.HasKey("UserId")
                        .HasName("pk_vrchat_user");

                    b.HasIndex("LastRefreshedAt")
                        .HasDatabaseName("ix_vrchat_user_last_refreshed");

                    b.HasIndex("LastSeenAt")
                        .HasDatabaseName("ix_vrchat_user_last_seen");

                    b.ToTable("vrchat_user", (string)null);
                });

            modelBuilder.Entity("Modbot.Core.Data.Entities.VRChatWorld", b =>
                {
                    b.Property<string>("WorldId")
                        .HasColumnType("text")
                        .HasColumnName("world_id");

                    b.Property<string>("AuthorId")
                        .HasColumnType("text")
                        .HasColumnName("author_id");

                    b.Property<string>("AuthorName")
                        .HasColumnType("text")
                        .HasColumnName("author_name");

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<DateTimeOffset?>("LastRefreshedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_refreshed_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<int?>("RecommendedCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("recommended_capacity");

                    b.Property<string>("RefreshError")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("refresh_error");

                    b.Property<string>("ReleaseStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("release_status");

                    b.Property<string>("Tags")
                        .HasColumnType("jsonb")
                        .HasColumnName("tags");

                    b.Property<string>("ThumbnailImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_image_url");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("WorldId")
                        .HasName("pk_vrchat_world");

                    b.HasIndex("FirstSeenAt")
                        .HasDatabaseName("ix_vrchat_world_unnamed")
                        .HasFilter("last_refreshed_at IS NULL");

                    b.ToTable("vrchat_world", (string)null);
                });

            modelBuilder.Entity("Modbot.Core.Data.Entities.ModbotUserRole", b =>
                {
                    b.HasOne("Modbot.Core.Data.Entities.ModbotRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_modbot_user_role_modbot_role_role_id");

                    b.HasOne("Modbot.Core.Data.Entities.ModbotUser", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_modbot_user_role_modbot_user_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Modbot.Core.Data.Entities.ModbotRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Modbot.Core.Data.Entities.ModbotUser", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
