using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Modbot.Core.Data.Migrations
{
    /// <summary>
    /// Drops <c>client_device.device_name</c>. The label a moderator typed for their own machine told
    /// an operator nothing they could act on -- whose device it is, its platform, its version and
    /// when it last reported answer every question the settings list is asked -- and it was one
    /// more piece of a person's data to hold. Generated by EF and checked by hand: one column, no
    /// other change.
    /// </summary>
    public partial class DropClientDeviceName : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "device_name",
                table: "client_device");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "device_name",
                table: "client_device",
                type: "character varying(128)",
                maxLength: 128,
                nullable: false,
                defaultValue: "");
        }
    }
}
