import { useMemo, useState } from 'react'
import { Code2 } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Card, CardContent } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import credits from '@/lib/credits.json'

/**
 * Credits: Modbot's own licence, the services it is built on, and every package it ships.
 *
 * The data is generated by `npm run credits` (scripts/credits.mjs) from the restored .NET solution
 * and a real Vite build, and bundled as JSON, so the page makes no request and cannot fail to load.
 * Open to everyone signed in, whatever their role: nothing here is about the group.
 */

type Credit = {
  name: string
  url: string | null
  licence: string | null
  version?: string
  source?: string | null
  usedBy?: string[]
  note?: string | null
}

type Group = { label?: string; items: Credit[] }

type Section = { title: string; groups: Group[] }

function split(items: (Credit & { direct: boolean })[]): Group[] {
  return [
    { label: 'Used directly', items: items.filter((i) => i.direct) },
    { label: 'Used by other packages', items: items.filter((i) => !i.direct) },
  ]
}

const SECTIONS: Section[] = [
  { title: 'Modbot', groups: [{ items: [credits.modbot] }] },
  { title: 'Services and data', groups: [{ items: credits.services }] },
  { title: 'Server and desktop packages', groups: split(credits.nuget) },
  { title: 'Web app packages', groups: split(credits.npm) },
  { title: 'Build tools', groups: [{ items: credits.buildTools }] },
]

function matches(item: Credit, words: string[]) {
  const haystack = [item.name, item.licence, item.version, ...(item.usedBy ?? [])].join(' ').toLowerCase()
  return words.every((w) => haystack.includes(w))
}

export function Credits() {
  const [query, setQuery] = useState('')

  const sections = useMemo(() => {
    const words = query.toLowerCase().split(/\s+/).filter(Boolean)
    return SECTIONS.map((s) => ({
      ...s,
      groups: s.groups
        .map((g) => ({ ...g, items: g.items.filter((i) => matches(i, words)) }))
        .filter((g) => g.items.length > 0),
    })).filter((s) => s.groups.length > 0)
  }, [query])

  return (
    <div className="flex w-full max-w-5xl flex-col gap-4">
      <Input
        type="search"
        placeholder="Search"
        aria-label="Search credits"
        value={query}
        onChange={(e) => setQuery(e.target.value)}
        className="sm:max-w-xs"
      />

      {sections.length === 0 && (
        <Card>
          <CardContent className="py-10 text-center text-muted-foreground">No matches</CardContent>
        </Card>
      )}

      {sections.map((s) => (
        <Card key={s.title} className="gap-3 py-4">
          <CardContent className="flex flex-col gap-3 px-4 sm:px-5">
            <h2 className="flex items-baseline gap-2 font-medium">
              {s.title}
              <span className="font-normal text-muted-foreground tabular-nums" style={{ fontSize: 'var(--text-small)' }}>
                {s.groups.reduce((n, g) => n + g.items.length, 0)}
              </span>
            </h2>

            {s.groups.map((g) => (
              <div key={g.label ?? s.title}>
                {g.label && (
                  <h3 className="pb-1 text-[0.6875rem] font-semibold uppercase tracking-wider text-muted-foreground/70">
                    {g.label}
                  </h3>
                )}
                <ul>
                  {g.items.map((item) => (
                    <Row key={`${item.name} ${item.version ?? ''}`} item={item} />
                  ))}
                </ul>
              </div>
            ))}
          </CardContent>
        </Card>
      ))}
    </div>
  )
}

/**
 * One credit. On a wide screen: name, version, licence in three aligned columns. On a narrow one
 * the three simply wrap, so a long package name gets the whole width rather than a sliver of it.
 */
function Row({ item }: { item: Credit }) {
  return (
    <li
      className="flex flex-wrap items-center gap-x-3 gap-y-0.5 border-b py-1.5 last:border-0 sm:grid sm:grid-cols-[minmax(0,1fr)_minmax(0,12rem)_auto]"
      style={{ borderBottomWidth: 'var(--hairline)' }}
    >
      <div className="flex min-w-0 flex-[1_1_100%] flex-wrap items-center gap-x-2 gap-y-1 sm:flex-auto">
        {item.url ? (
          <a href={item.url} target="_blank" rel="noreferrer" className="font-medium [overflow-wrap:anywhere] hover:underline">
            {item.name}
          </a>
        ) : (
          <span className="font-medium [overflow-wrap:anywhere]">{item.name}</span>
        )}
        {item.source && (
          <a
            href={item.source}
            target="_blank"
            rel="noreferrer"
            title="Source"
            aria-label={`${item.name} source`}
            className="text-muted-foreground hover:text-foreground"
          >
            <Code2 className="size-3.5" />
          </a>
        )}
        {item.usedBy?.map((part) => (
          <Badge key={part} variant="outline" className="font-normal">
            {part}
          </Badge>
        ))}
      </div>

      <span
        className="min-w-0 truncate font-mono text-muted-foreground"
        style={{ fontSize: 'var(--text-small)' }}
        title={item.version}
      >
        {item.version}
      </span>

      <div className="ml-auto sm:justify-self-end">
        {item.licence && (
          <Badge variant="secondary" className="font-mono font-normal">
            {item.licence}
          </Badge>
        )}
      </div>

      {item.note && (
        <p className="basis-full text-muted-foreground sm:col-span-full" style={{ fontSize: 'var(--text-small)' }}>
          {item.note}
        </p>
      )}
    </li>
  )
}
