// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modbot.My.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modbot.My.Data.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20260914144843_CreateRegistry")]
    partial class CreateRegistry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modbot.My.Features.Instances.RegisteredInstance", b =>
                {
                    b.Property<string>("InstanceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("instance_id");

                    b.Property<bool>("AnalyticsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("analytics_enabled");

                    b.Property<bool?>("DiscordConnected")
                        .HasColumnType("boolean")
                        .HasColumnName("discord_connected");

                    b.Property<string>("InstanceUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("instance_url");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<DateTimeOffset?>("LastUsageReportAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_usage_report_at");

                    b.Property<int?>("PairedClients")
                        .HasColumnType("integer")
                        .HasColumnName("paired_clients");

                    b.Property<int?>("RateLimitColdStops")
                        .HasColumnType("integer")
                        .HasColumnName("rate_limit_cold_stops");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<string>("ScaleBucket")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("scale_bucket");

                    b.PrimitiveCollection<List<string>>("TermListsImported")
                        .HasColumnType("text[]")
                        .HasColumnName("term_lists_imported");

                    b.Property<string>("Version")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("version");

                    b.Property<int?>("WafBlocks")
                        .HasColumnType("integer")
                        .HasColumnName("waf_blocks");

                    b.HasKey("InstanceId")
                        .HasName("pk_registered_instance");

                    b.HasIndex("InstanceUrl")
                        .HasDatabaseName("ix_registered_instance_instance_url");

                    b.HasIndex("LastSeenAt")
                        .HasDatabaseName("ix_registered_instance_last_seen_at");

                    b.ToTable("registered_instance", (string)null);
                });

            modelBuilder.Entity("Modbot.My.Features.RegisterPage.RegisterPageInstance", b =>
                {
                    b.Property<string>("InstanceUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("instance_url");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<int>("Visits")
                        .HasColumnType("integer")
                        .HasColumnName("visits");

                    b.HasKey("InstanceUrl")
                        .HasName("pk_register_page_instance");

                    b.HasIndex("LastSeenAt")
                        .HasDatabaseName("ix_register_page_instance_last_seen_at");

                    b.ToTable("register_page_instance", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
