import { useMemo, useState } from 'react'
import { CreditCard, type Credit } from '@/components/credits/CreditRow'
import { Card } from '@/components/ui/card'
import { EmptyRow, PanelGrid } from '@/components/PanelGrid'
import { Input } from '@/components/ui/input'
import credits from '@/lib/credits.json'

/**
 * Every package Modbot ships, with its version and its licence.
 *
 * The data is generated by `npm run credits` (scripts/credits.mjs) from the restored .NET solution
 * and a real Vite build, and bundled as JSON, so the page makes no request and cannot fail to load.
 */

type Group = { label?: string; items: Credit[] }

type Section = { title: string; groups: Group[] }

function split(items: (Credit & { direct: boolean })[]): Group[] {
  return [
    { label: 'Used directly', items: items.filter((i) => i.direct) },
    { label: 'Used by other packages', items: items.filter((i) => !i.direct) },
  ]
}

const SECTIONS: Section[] = [
  { title: 'Server and desktop packages', groups: split(credits.nuget) },
  { title: 'Web app packages', groups: split(credits.npm) },
  { title: 'Build tools', groups: [{ items: credits.buildTools }] },
]

function matches(item: Credit, words: string[]) {
  const haystack = [item.name, item.licence, item.version, ...(item.usedBy ?? [])].join(' ').toLowerCase()
  return words.every((w) => haystack.includes(w))
}

export function Libraries() {
  const [query, setQuery] = useState('')

  const sections = useMemo(() => {
    const words = query.toLowerCase().split(/\s+/).filter(Boolean)
    return SECTIONS.map((s) => ({
      ...s,
      groups: s.groups
        .map((g) => ({ ...g, items: g.items.filter((i) => matches(i, words)) }))
        .filter((g) => g.items.length > 0),
    })).filter((s) => s.groups.length > 0)
  }, [query])

  return (
    <div className="flex flex-col gap-3">
      <Input
        type="search"
        placeholder="Search"
        aria-label="Search packages"
        value={query}
        onChange={(e) => setQuery(e.target.value)}
        className="sm:max-w-xs"
      />

      {sections.length === 0 ? (
        <Card>
          <EmptyRow>No matches</EmptyRow>
        </Card>
      ) : (
        <PanelGrid className="grid-cols-1">
          {sections.map((s) => (
            <CreditCard key={s.title} title={s.title} groups={s.groups} />
          ))}
        </PanelGrid>
      )}
    </div>
  )
}
